"""Add DCNo to invoiceItem and add indexes to invoice, item, invoiceItem

Revision ID: 4e06ec8305d7
Revises: a0d9d430d810
Create Date: 2025-08-30 11:07:24.327239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e06ec8305d7'
down_revision = 'a0d9d430d810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_createdAt'), ['createdAt'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_customerId'), ['customerId'], unique=False)

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dcNo', sa.String(length=64), nullable=True))
        batch_op.create_index('ix_invoiceItem_invoice_item', ['invoiceId', 'itemId'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_dcNo'), ['dcNo'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_invoiceId'), ['invoiceId'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_itemId'), ['itemId'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_name'))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_itemId'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoiceId'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_dcNo'))
        batch_op.drop_index('ix_invoiceItem_invoice_item')
        batch_op.drop_column('dcNo')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_customerId'))
        batch_op.drop_index(batch_op.f('ix_invoice_createdAt'))

    # ### end Alembic commands ###
