"""Add exclude_phone, gst, addr to invoice

Revision ID: b1aa5b3f6449
Revises: f1c605ba9ad9
Create Date: 2025-09-02 19:59:44.796698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1aa5b3f6449'
down_revision = 'f1c605ba9ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_phone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exclude_gst', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exclude_addr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('exclude_addr')
        batch_op.drop_column('exclude_gst')
        batch_op.drop_column('exclude_phone')

    # ### end Alembic commands ###
