"""Rename item.hsn to sku and make it incremental

Revision ID: ef058e77c8c2
Revises: f2752132036f
Create Date: 2025-08-30 17:02:01.404994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef058e77c8c2'
down_revision = 'f2752132036f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_item_sku'), ['sku'], unique=True)
        batch_op.drop_column('hsn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_item_sku'))
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
