"""add soft-delete to customer

Revision ID: f1c605ba9ad9
Revises: ef058e77c8c2
Create Date: 2025-09-01 10:44:53.381907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c605ba9ad9'
down_revision = 'ef058e77c8c2'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns with a temporary server_default so existing rows get a value
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('deletedAt', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_customer_deletedAt', ['deletedAt'], unique=False)
        batch_op.create_index('ix_customer_isDeleted', ['isDeleted'], unique=False)

    # Drop the server_default so inserts rely on ORM defaults going forward
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('isDeleted', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_isDeleted'))
        batch_op.drop_index(batch_op.f('ix_customer_deletedAt'))
        batch_op.drop_column('deletedAt')
        batch_op.drop_column('isDeleted')

    # ### end Alembic commands ###
